### ISSUE TITLE
关于论文的relevance score

### ISSUE THREAD

**Issue by firedie000** [RUCAIBox/REAR#1]
hello 论文的4.1.2中有提到使用了相关性分数，然后把它转为embedding再和q、d一起生成answer。但在代码中相关性分数似乎只做了最终排序的参考，并没有转化为embedding。请问下这是为什么呢

**Comment by yhao-wang** [comment]
您好，您可以仔细看一下inference的代码，是将生成的分数映射为embedding返回的。

**Comment by yhao-wang** [comment]
具体内容请参考[codes](https://github.com/RUCAIBox/REAR/blob/master/rear/src/vllm_rear.py)，有任何疑问欢迎您提出

**Comment by kaishxu** [comment]
你好，想请问下，训练的时候就不需要这么操作吗？可以把那行代码写出来吗？

**Comment by kaishxu** [comment]
结合代码来看，论文中所谓的将相关性分数转成embedding，其实是先通过阈值转换成是否相关的token，再输入到模型中，是这样吗？所以训练的时候不用单独操作，而inference的时候需要额外补充相关与否的token？

**Comment by yhao-wang** [comment]
您的理解是正确的。

训练过程是有相关操作的，您可以看一下 [rear/src/modeling_rearllama.py](https://github.com/RUCAIBox/REAR/blob/master/rear/src/modeling_rearllama.py)
