### ISSUE TITLE
What does the training set look like?

### ISSUE THREAD

**Issue by liumc14** [RUCAIBox/REAR#11]
What does the training set look like? I saw that the data in the training set includes input, output, and score in the code. How many reference documents are there in the input? Does it correspond to an answer based on a reference document mentioned in the paper? And what is the score here?
https: /github.com/RUCAIBox/REAR/blob/73eb821581c27b7eed2ed05bf998b98f20041091/rear/src/dataset.py#L82

**Comment by yhao-wang** [comment]
Hello, thank you for following our work. We have not yet made the training data public and will open it up as soon as possible.

**Comment by liumc14** [comment]
> Hello, thank you for following our work. We have not yet made the training data public and will open it up as soon as possible.

Thank you for your reply, according to the description in the paper: “The
The dataset is constructed using the two highest-scoring
positive documents and six negative documents”
So each question corresponds to 8 documents in total?Does a document generate an answer only at inference time? Or is it the same during training? One document corresponds to one answer.

**Comment by yhao-wang** [comment]
Thank you for reaching out. 

I'm not entirely sure if I fully understand your question. During the training phase, we provide 8 documents per query to facilitate noise-resistance training of the model. In the inference phase, we utilize the top K documents returned by the retriever for each query.  -- if this is your question.

我没完全理解您的意思。在训练阶段，我们会为每个查询提供8篇文档，以帮助模型进行抗噪声（noise-resistance training）训练。在推理阶段，我们将使用检索器返回的每个查询的前K篇文档。您是想问这个吗？
