### ISSUE TITLE
Some issues about loading pretrained model weights for rank head in inference.

### ISSUE THREAD

**Issue by heounjunee** [RUCAIBox/REAR#13]
Hello.
In the Inference situation, the weight loading part of the trained model weights for rank head is missing.

There is a load_weights function (def load_weights) in class LlamaForLear(LlamaForCausalLM) in vllm_rear.py, but no code exists to call it.

Thank you.

**Comment by yhao-wang** [comment]
Hello,

You need to refer to the quick start section in the README and use the checkpoint we uploaded on HuggingFace.
