### ISSUE TITLE
Problems encountered during example reasoning

### ISSUE THREAD

**Issue by liumc14** [RUCAIBox/REAR#14]
When using the given example for inference, the model is loaded in vllm. How to generate the model by passing in prompt, which is text? Shouldn't the input to model.generate() be the ID after segmentation？
https://github.com/RUCAIBox/REAR/blob/6676ae002374c92e9021422d1d6b4a60dd04f749/rear/src/inf.py#L36

**Comment by yhao-wang** [comment]
The type of the parameter \(\text{prompt}\) can indeed be a string or a list of strings. I hope this addresses your query.

Should you have further questions or need additional clarification, feel free to ask in Chinese. It facilitates a more precise understanding of your concerns on my part.

**Comment by liumc14** [comment]
> The type of the parameter (\text{prompt}) can indeed be a string or a list of strings. I hope this addresses your query.
> 
> Should you have further questions or need additional clarification, feel free to ask in Chinese. It facilitates a more precise understanding of your concerns on my part.

谢谢您的回复，因为我的设备落后，GPU暂不支持vllm，因此我想使用get_model的方法来加载模型而非示例中使用的get_vllm_model("RUCAIBox/rear-llama-7b-hf")，但是似乎会报错提示我outputs = model.generate(prompt, sampling_params=generation_config, use_tqdm=False) 在执行时prompt是个列表而非tensor向量，所以我才困惑于model.generate（）函数不是应该对分词后的id向量处理吗？  请您帮助我解惑，谢谢！！！

**Comment by yhao-wang** [comment]
我们目前暂未实现不使用vLLM推理的脚本，可能需要你参考论文和我们提供的代码完善一下。如果你还有新的问题，欢迎继续提问
