### ISSUE TITLE
ImportError: ~/.conda/envs/py39/lib/python3.9/site-packages/vllm/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

### ISSUE THREAD

**Issue by Sakura718** [RUCAIBox/REAR#15]
`ImportError: ~/.conda/envs/py39/lib/python3.9/site-packages/vllm/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi`
在 #3 中作者提到使用 `pip install -r requirements.txt`即可解决，可是我在解决一系列包的版本冲突（特别是flash-attn==2.3.5）之后，还是报了如上所述的错误，以下是我下载的包的版本
```
Name: vllm
Version: 0.2.3
Name: transformers
Version: 4.38.0
Name: datasets
Version: 2.14.3
Name: flash-attn
Version: 2.3.5
Name: torch
Version: 2.4.0
Name: deepspeed
Version: 0.15.5+unknown
Name: accelerate
Version: 0.27.2
Name: safetensors
Version: 0.4.5
```
麻烦作者抽空解答一下，非常感谢！

**Comment by yhao-wang** [comment]
您好，您使用的cuda版本和pytorch版本都较新，可能会出现各种问题。您可以先尝试一下能否正常使用VLLM跑Llama-2-7b-hf等模型

**Comment by Sakura718** [comment]
> 您好，您使用的cuda版本和pytorch版本都较新，可能会出现各种问题。您可以先尝试一下能否正常使用VLLM跑Llama-2-7b-hf等模型

好的好的，可以顺便问一下作者您用的cuda版本和pytorch版本都是多少吗，谢谢！

**Comment by yhao-wang** [comment]
您好，我查看了一下：
vllm                                    0.2.3
torch                                  2.1.2
torchaudio                         2.1.0+cu121
torchvision                        0.16.0+cu121

**Comment by hxy-62** [comment]
same issue

**Comment by hxy-62** [comment]
> > 您好，您使用的cuda版本和pytorch版本都较新，可能会出现各种问题。您可以先尝试一下能否正常使用VLLM跑Llama-2-7b-hf等模型
> 
> 好的好的，可以顺便问一下作者您用的cuda版本和pytorch版本都是多少吗，谢谢！

请问你解决了吗，我这边也很多包冲突

**Comment by yhao-wang** [comment]
请问您可以正常使用vLLM 0.2.3跑Llama-2-7b-hf等模型吗



---Original---
From: ***@***.***&gt;
Date: Tue, Dec 10, 2024 12:01 PM
To: ***@***.***&gt;;
Cc: "Yuhao ***@***.******@***.***&gt;;
Subject: Re: [RUCAIBox/REAR] ImportError: ~/.conda/envs/py39/lib/python3.9/site-packages/vllm/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi (Issue #15)




   
您好，您使用的cuda版本和pytorch版本都较新，可能会出现各种问题。您可以先尝试一下能否正常使用VLLM跑Llama-2-7b-hf等模型
  
好的好的，可以顺便问一下作者您用的cuda版本和pytorch版本都是多少吗，谢谢！
  
请问你解决了吗，我这边也很多包冲突

**Comment by Sakura718** [comment]
> > > 您好，您使用的cuda版本和pytorch版本都较新，可能会出现各种问题。您可以先尝试一下能否正常使用VLLM跑Llama-2-7b-hf等模型
> > 
> > 
> > 好的好的，可以顺便问一下作者您用的cuda版本和pytorch版本都是多少吗，谢谢！
> 
> 请问你解决了吗，我这边也很多包冲突

没有，试了很久都不行，就没管了😂

**Comment by yhao-wang** [comment]
请问您可以直接正常运行vLLM0.2.3跑其原始支持的模型吗，例如Llama2。我这边的没有修改底层的cuda算子，所以如果vllm 0.2.3可以正常运行的话，应该是没有问题的

抱歉版本兼容的问题

**Comment by hxy-62** [comment]
> 请问您可以直接正常运行vLLM0.2.3跑其原始支持的模型吗，例如Llama2。我这边的没有修改底层的cuda算子，所以如果vllm 0.2.3可以正常运行的话，应该是没有问题的
> 
> 抱歉版本兼容的问题

我这边可以运行了，手动安装的包，pip的时候加上--no-deps
