### ISSUE TITLE
Many small errors

### ISSUE THREAD

**Issue by jackwwy** [RUCAIBox/REAR#2]
requirements中transformers打错
routing文件中存在大量列表操作和字典操作不分的情况
inf文件添加无关的语句，比如 beta = model.beta model.beta = None

**Comment by yhao-wang** [comment]
抱歉对您复现带来了困扰，在开源过程中由于原始代码规模较大，我进行了一些简化和合并，可能带来了一些错误。由于原始代码在不断的尝试过程中函数冗长，变量名混乱，重写代码本身是为了增加代码的可读性，并非您所提出的增加复现的障碍。您指出的累赘代码原本有其它方向上的尝试。如果您需要我可以把原始代码邮件发送给您。我将再次测试是否有推理方面的bug，感谢您的批评。

**Comment by yhao-wang** [comment]
您好，Inference相关bug已经修复，感谢您的意见

**Comment by jackwwy** [comment]
preds = [dic['preds'][0] for dic in res]> 您指出的“大量列表操作和字典操作不分的情况”，是指哪一部分呢？我将修复一下相关代码

routing.py中s1,s2函数中变量res是列表，但是在if语句中被当做字典使用。
`if res['reference'] is not None:
            em.append(res['response']['con_answer']['EM'])
            f1.append(res['response']['con_answer']['F1'])`
在consistency函数中，dict函数漏掉t
`dic.update(dic(response=response))`
inf.py文件，get_perplexity函数中dic的索引错误preds应该改为pred
`preds = [dic['preds'][0] for dic in res]`
另外get_model函数，
`model = LlamaForCausalLM.from_pretrained(model_path, **kwargs)`好像需要把模型放在GPU上，否则报运行错误`model = LlamaForCausalLM.from_pretrained(model_path, **kwargs).to('cuda')`

**Comment by yhao-wang** [comment]
您好，您提到的错误已经在刚刚的提交中修复 commit 7bcd1906bf82e2cd44dac29753ccfce74b4e60d8

再次感谢！
