### ISSUE TITLE
ImportError:

### ISSUE THREAD

**Issue by hxy-62** [RUCAIBox/REAR#3]
ImportError: /home/hxy/enter/envs/rear_proj/lib/python3.9/site-packages/vllm/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15to_dtype_layout4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEEbbNS6_INS5_12MemoryFormatEEE

**Comment by yhao-wang** [comment]
Please run ```pip install -r requirements.txt```
