### ISSUE TITLE
请问训练数据有公开的计划吗

### ISSUE THREAD

**Issue by sjchasel** [RUCAIBox/REAR#7]

**Comment by sjchasel** [comment]
对于多个answer的数据，训练的时候是进行数据增强还是每个问题随机采样一个answer呢？

**Comment by yhao-wang** [comment]
根据我们的实验，不同的策略影响不是很大。训练的数据我们还在处理，将尽快开源。

**Comment by jingfanke** [comment]
+1，期待开源训练集。是否可以给更多关于处理NQ数据集的细节？
