### ISSUE TITLE
对REAR中的Rank Head有疑惑

### ISSUE THREAD

**Issue by cuichenxu** [RUCAIBox/REAR#8]
有关论文中的Figure 1有一个小疑问：
1、将query-document输入进入LLM Decoder，指的是
· 进行了一次推理，不做最后一步将tensor转化为word吗？
· 还是利用LLM的Decoder转换为embedding？（没太懂是用Encoder还是Decoder？论文中写的是Decoder）

**Comment by yhao-wang** [comment]
您好，您的两个理解都正确吧。
LLaMA是decoder-only架构，因而是Decoder

**Comment by cuichenxu** [comment]
> 您好，您的两个理解都正确吧。 LLaMA是decoder-only架构，因而是Decoder

感谢，昨天考虑到了llama是decoder-only结构，感谢解惑。
